//
// ComicPrice.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct ComicPrice: Codable {

    /** A description of the price (e.g. print price, digital price). */
    public var type: String?
    /** The price (all prices in USD). */
    public var price: Float?

    public init(type: String?, price: Float?) {
        self.type = type
        self.price = price
    }


}

