//
// ModelCharacter.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct ModelCharacter: Codable {

    /** The unique ID of the character resource. */
    public var _id: Int?
    /** The name of the character. */
    public var name: String?
    /** A short bio or description of the character. */
    public var _description: String?
    /** The date the resource was most recently modified. */
    public var modified: Date?
    /** The canonical URL identifier for this resource. */
    public var resourceURI: String?
    /** A set of public web site URLs for the resource. */
    public var urls: [Url]?
    /** The representative image for this character. */
    public var thumbnail: Image?
    /** A resource list containing comics which feature this character. */
    public var comics: ComicList?
    /** A resource list of stories in which this character appears. */
    public var stories: StoryList?
    /** A resource list of events in which this character appears. */
    public var events: EventList?
    /** A resource list of series in which this character appears. */
    public var series: SeriesList?

    public init(_id: Int?, name: String?, _description: String?, modified: Date?, resourceURI: String?, urls: [Url]?, thumbnail: Image?, comics: ComicList?, stories: StoryList?, events: EventList?, series: SeriesList?) {
        self._id = _id
        self.name = name
        self._description = _description
        self.modified = modified
        self.resourceURI = resourceURI
        self.urls = urls
        self.thumbnail = thumbnail
        self.comics = comics
        self.stories = stories
        self.events = events
        self.series = series
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case name
        case _description = "description"
        case modified
        case resourceURI
        case urls
        case thumbnail
        case comics
        case stories
        case events
        case series
    }


}

