//
// Series.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct Series: Codable {

    /** The unique ID of the series resource. */
    public var _id: Int?
    /** The canonical title of the series. */
    public var title: String?
    /** A description of the series. */
    public var _description: String?
    /** The canonical URL identifier for this resource. */
    public var resourceURI: String?
    /** A set of public web site URLs for the resource. */
    public var urls: [Url]?
    /** The first year of publication for the series. */
    public var startYear: Int?
    /** The last year of publication for the series (conventionally, 2099 for ongoing series) . */
    public var endYear: Int?
    /** The age-appropriateness rating for the series. */
    public var rating: String?
    /** The date the resource was most recently modified. */
    public var modified: Date?
    /** The representative image for this series. */
    public var thumbnail: Image?
    /** A resource list containing comics in this series. */
    public var comics: ComicList?
    /** A resource list containing stories which occur in comics in this series. */
    public var stories: StoryList?
    /** A resource list containing events which take place in comics in this series. */
    public var events: EventList?
    /** A resource list containing characters which appear in comics in this series. */
    public var characters: CharacterList?
    /** A resource list of creators whose work appears in comics in this series. */
    public var creators: CreatorList?
    /** A summary representation of the series which follows this series. */
    public var next: SeriesSummary?
    /** A summary representation of the series which preceded this series. */
    public var previous: SeriesSummary?

    public init(_id: Int?, title: String?, _description: String?, resourceURI: String?, urls: [Url]?, startYear: Int?, endYear: Int?, rating: String?, modified: Date?, thumbnail: Image?, comics: ComicList?, stories: StoryList?, events: EventList?, characters: CharacterList?, creators: CreatorList?, next: SeriesSummary?, previous: SeriesSummary?) {
        self._id = _id
        self.title = title
        self._description = _description
        self.resourceURI = resourceURI
        self.urls = urls
        self.startYear = startYear
        self.endYear = endYear
        self.rating = rating
        self.modified = modified
        self.thumbnail = thumbnail
        self.comics = comics
        self.stories = stories
        self.events = events
        self.characters = characters
        self.creators = creators
        self.next = next
        self.previous = previous
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case title
        case _description = "description"
        case resourceURI
        case urls
        case startYear
        case endYear
        case rating
        case modified
        case thumbnail
        case comics
        case stories
        case events
        case characters
        case creators
        case next
        case previous
    }


}

