//
// Story.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct Story: Codable {

    /** The unique ID of the story resource. */
    public var _id: Int?
    /** The story title. */
    public var title: String?
    /** A short description of the story. */
    public var _description: String?
    /** The canonical URL identifier for this resource.  */
    public var resourceURI: String?
    /** The story type e.g. interior story, cover, text story. */
    public var type: String?
    /** The date the resource was most recently modified. */
    public var modified: Date?
    /** The representative image for this story. */
    public var thumbnail: Image?
    /** A resource list containing comics in which this story takes place. */
    public var comics: ComicList?
    /** A resource list containing series in which this story appears. */
    public var series: SeriesList?
    /** A resource list of the events in which this story appears. */
    public var events: EventList?
    /** A resource list of characters which appear in this story. */
    public var characters: CharacterList?
    /** A resource list of creators who worked on this story. */
    public var creators: CreatorList?
    /** A summary representation of the issue in which this story was originally published. */
    public var originalissue: ComicSummary?

    public init(_id: Int?, title: String?, _description: String?, resourceURI: String?, type: String?, modified: Date?, thumbnail: Image?, comics: ComicList?, series: SeriesList?, events: EventList?, characters: CharacterList?, creators: CreatorList?, originalissue: ComicSummary?) {
        self._id = _id
        self.title = title
        self._description = _description
        self.resourceURI = resourceURI
        self.type = type
        self.modified = modified
        self.thumbnail = thumbnail
        self.comics = comics
        self.series = series
        self.events = events
        self.characters = characters
        self.creators = creators
        self.originalissue = originalissue
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case title
        case _description = "description"
        case resourceURI
        case type
        case modified
        case thumbnail
        case comics
        case series
        case events
        case characters
        case creators
        case originalissue
    }


}

